import { Listing } from "src/types";

export let properties: Listing[] = [
  {
    id: "1",
    image:
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=300&h=200&fit=crop",
    title: "Charming 3-Bedroom Home in Willow Creek",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1800,
    price: 450000,
    status: "available",
    dateListed: "2024-12-01",
    amenities: ["parking", "garden", "fireplace"],
    utilities: ["water", "electricity", "internet"],
    location: "willow-creek",
    type: "house",
    description:
      "Beautiful family home with modern updates and spacious backyard.",
  },
  {
    id: "2",
    image:
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=300&h=200&fit=crop",
    title: "Modern Apartment with City View",
    bedrooms: 1,
    bathrooms: 1,
    sqft: 750,
    price: 325000,
    status: "available",
    dateListed: "2024-11-28",
    amenities: ["pool", "gym", "balcony"],
    utilities: ["water", "electricity", "gas", "internet"],
    location: "downtown",
    type: "apartment",
    description: "Stunning city views from this modern downtown apartment.",
  },
  {
    id: "3",
    image:
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=300&h=200&fit=crop",
    title: "Spacious Family House in Green Meadows",
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2500,
    price: 675000,
    status: "pending",
    dateListed: "2024-11-25",
    amenities: ["parking", "garden", "pool"],
    utilities: ["water", "electricity", "gas"],
    location: "green-meadows",
    type: "house",
    description: "Perfect family home with pool and large garden.",
  },
  {
    id: "4",
    image:
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=300&h=200&fit=crop",
    title: "Cozy Condo in Downtown District",
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1200,
    price: 425000,
    status: "available",
    dateListed: "2024-12-03",
    amenities: ["gym", "balcony", "concierge"],
    utilities: ["water", "electricity", "internet"],
    location: "downtown",
    type: "condo",
    description: "Luxury condo with premium amenities and concierge service.",
  },
  {
    id: "5",
    image:
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=300&h=200&fit=crop",
    title: "Luxury Estate with Pool and Garden",
    bedrooms: 5,
    bathrooms: 4,
    sqft: 4000,
    price: 1200000,
    status: "sold",
    dateListed: "2024-11-20",
    amenities: ["pool", "garden", "garage", "fireplace"],
    utilities: ["water", "electricity", "gas", "internet"],
    location: "green-meadows",
    type: "house",
    description: "Magnificent estate with luxury finishes throughout.",
  },
  {
    id: "6",
    image:
      "https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=300&h=200&fit=crop",
    title: "Renovated Townhouse in Historic Area",
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1600,
    price: 525000,
    status: "available",
    dateListed: "2024-11-30",
    amenities: ["parking", "fireplace"],
    utilities: ["water", "electricity", "gas", "internet"],
    location: "historic",
    type: "townhouse",
    description: "Beautifully renovated historic townhouse with character.",
  },
  {
    id: "7",
    image:
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=300&h=200&fit=crop",
    title: "Studio Apartment in Arts District",
    bedrooms: 0,
    bathrooms: 1,
    sqft: 500,
    price: 275000,
    status: "available",
    dateListed: "2024-12-05",
    amenities: ["gym", "rooftop"],
    utilities: ["water", "electricity", "internet"],
    location: "downtown",
    type: "apartment",
    description: "Trendy studio in the heart of the arts district.",
  },
  {
    id: "8",
    image:
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=300&h=200&fit=crop",
    title: "Contemporary 2BR in Willow Creek",
    bedrooms: 2,
    bathrooms: 1,
    sqft: 1000,
    price: 385000,
    status: "pending",
    dateListed: "2024-11-22",
    amenities: ["parking", "balcony"],
    utilities: ["electricity", "gas", "internet"],
    location: "willow-creek",
    type: "condo",
    description: "Modern design with open floor plan and natural light.",
  },
];
