import ResetPassword from "./ResetPassword/ResetPassword";
import Login from "./Login/Login";
import Register from "./Register/Register";
import OAuthCallback from "./OAuthCallback/OAuthCallback";
import ForgotPassword from "./ForgetPassword/ForgetPassword";
import Error from "./Error/Error";
import VerifyEmail from "./VerifiyEmail/VerifiyEmail";
import PaymentForm from "./PaymentForm/PaymentForm";
export {ResetPassword, Login, Register,OAuthCallback,ForgotPassword,Error,VerifyEmail,PaymentForm};